blank_issues_enabled: false
contact_links:
  - name: Vulnerabilidade de segurança
    url: https://docs.github.com/pt/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability
    about: Relate em privado, não em issue pública.
